modLoader="bml_java_fml"
loaderVersion="${forge_loader_version_range}"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="${mod_id}-icon.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
server_mod_instance_class_name="${group}.${mod_id}.IronShulkerBoxesModInstance"
client_mod_instance_class_name="${group}.${mod_id}.client.IronShulkerBoxesClientModInstance"
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="mdcdi1315_base_mods_lib"
mandatory=true
versionRange="[${base_mods_lib_version},)"
ordering="AFTER"
side="BOTH"